<?php
/**
 * Implementation of hook_menu().
 */
function asce_pages_menu() {
//  $items['admin/asce/list-cck-fields'] = array(
//    'title' => 'List CCK Fields',
//    'description' => t('Update test for testing notifications.'),
//    'access arguments' => array('configure ASCE Mobile Tools'),
//    'page callback' => 'asce_cck_list_cck_fields',
//  );
//  return $items;
}

/**
 * Implementation of hook_token_list().
 */
function asce_pages_token_list($type = 'all') {
  if ($type == 'user' || $type == 'all') {
    $tokens['user']['user-name-dynamic']     = t("The login name of the user account. If Anonymous it will be blank.");
    $tokens['user']['user-name-full']     = t("Full name of user based on profile data. If Anonymous it will be blank.");  
    return $tokens;
  }
}

/**
 * Implementation of hook_token_values().
 */
function asce_pages_token_values($type, $object = NULL, $options = array()) {
  $values = array();
  switch ($type) {
    case 'user':
      if (isset($object)) {
        $account = $object;
      }
      else {
        global $user;
        $account = user_load(array('uid' => $user->uid));
      }
      $full_name = $account->profile_nick_name ? $account->profile_nick_name : $account->profile_first_name; 
      $full_name .= ' ' . $account->profile_last_name;
      if(empty($full_name)) {
      	$full_name = $account->name;
      }
      // Adjust for the anonymous user name.
      if (!$account->uid && !$account->name) {
        $full_name = '&nbsp';
      }
      if($account->name == 'Anonymous') {
      	$full_name = '';
      }
      $values['user-name-full']     = check_plain($full_name);
      break;
  }
  return $values;
}