<?php

/**
 * Implementation of hook_schema().
 */
function asce_views_schema() {
  $schema = array();
  return $schema;
}

/**
 * Implementation of hook_uninstall().
 */
function asce_views_uninstall() {
  // Remove all database tables.
  drupal_uninstall_schema('asce_views');
}

/**
 * Implementation of hook_install().
 */
function asce_views_install() {
  db_query("UPDATE {system} SET weight = 100 WHERE name = 'asce_views'");
}
