<?php

/**
 * @file
 *  LoginToboggan module
 *
 * This module enhances the configuration abilities of Drupal's default login system.
 */

/**
 * @todo
 *
 */

/**
 * @wishlist
 *
 */

/**
 * @defgroup logintoboggan_core Core drupal hooks
 */

function email_as_username_form_alter(&$form, &$form_state, $form_id) {
  dpm($form);
  dpm($form_state);
  dpm($form_id);
  $form['#access'] = FALSE;
  $form['#required'] = FALSE;
}