<?php

// $Id: domain_session_default.module,v 1.2.2.5 2010/11/17 21:08:33 jhedstrom Exp $

/**
 * @file
 * The Domain Session Default module provides default domain
 * functionality for unauthenticated users via sessions.
 */

/**
 * Impelementation of hook_user().
 */
function domain_session_default_user($op, &$edit, &$account, $category = NULL) {
  switch ($op) {
    case 'load':
      // only interested in uid = 0 accounts, and have cookies enabled.
      if ($account->uid == 0 && ($sid = session_api_get_sid())) {
        $account->default_domain = domain_session_default_session_default($sid);
      }
      break;
  }
}

/**
 * Get the domain associated with the session.
 * @param integer $sid - The Session API ID
 * @return The domain ID
 */
function domain_session_default_session_default($sid) {
  return db_result(db_query("SELECT domain_id FROM {domain_session_default} WHERE sid = %d", $sid));
}

/**
 * Save session/domain_id mapping.
 */
function _domain_session_default_session_update($account) {
  if ($sid = session_api_get_sid()) {
    $record = new stdClass();
    $record->sid = $sid;
    $record->domain_id = $account->default_domain;

    // test for existing record
    if ($sid == db_result(db_query("SELECT sid FROM {domain_session_default} WHERE sid = %d", $sid))) {
      // update
      $update = array('sid');
    }
    drupal_write_record('domain_session_default', $record, $update);
  }
}

/**
 * Implementation of hook_domainupdate().
 */
function domain_session_default_domainupdate($op, $domain, $form_state = array()) {
  switch ($op) {
    case 'delete':
      // reset any users using this domain back to the primary domain
      db_query("DELETE FROM {domain_session_default} WHERE domain_id = %d", $domain['domain_id']);
  }
}

/**
 * Implementation of hook_session_api_cleanup().
 */
function domain_session_default_session_api_cleanup($sids) {
  if (!empty($sids)) {
    db_query("DELETE FROM {domain_session_default} WHERE sid IN (%s)", array(':sids' => implode(',', $sids)));
  }
}

