<?php
// $Id$

function asce_update_form_alter(&$form, &$form_state, $form_id) {
  if ($types = node_get_types()) {
    foreach (array_keys($types) as $type) {
      $form_ids[]= $type .'_node_form';
    }
  }
  if (in_array($form_id, $form_ids)) {
    $form['save_changed'] = array('#type' => value, '#value' => $form['#node']->changed);
    $form['notifications']['#collapsible'] = TRUE;
    if (user_access('set update flag')) {
    	$form['notifications']['#weight'] = -10;
    	$form['notifications']['do_not_update'] = array(
        '#type'          => 'checkbox',
        '#title'         => t('Do not flag as updated.'),
        '#default_value' => $default,
    	);
    }
  }
}

function asce_update_nodeapi(&$node, $op, $a3 = NULL, $a4 = NULL) {
	if ($op == 'update') {		
		if ($node->do_not_update) {
			$node->changed = $node->save_changed;
			drupal_write_record('node', $node, 'nid');
		}
	}

}

function asce_update_perm() {
	return array('set update flag');
}