<?php
// $Id$

function asce_login_menu() {
	// Callback for handling access denied redirection.
  $items['asce/denied'] = array(
    'access callback' => TRUE,
    'page callback' => 'asce_login_denied',
    'title' => 'Access denied',
    'type' => MENU_CALLBACK,
  );
	$items['new-account'] = array(
    'access callback' => TRUE,
    'page callback' => 'asce_login_new_account',
    'title' => 'New Account',
    'type' => MENU_CALLBACK,
  );
  return $items;
}

/**
 * Implementation of module_preprocess_hook().
 * This preprocess override will allow a user who is logging in to go directly to the page from
 * which they logged in from.
 */
function asce_login_preprocess_page(&$variables) {
	foreach($variables['primary_links'] as $menu => $item) {
		if ($item['title'] == 'Login') {
			$variables['primary_links'][$menu]['query'] = drupal_get_destination();
		}
	}
}

//function asce_login_ctools_plugin_directory($module, $plugin) {
//	if ($module == 'panels' && $plugin == 'layouts') {
//		//dsm($plugin);
//    return "plugins/$plugin";
//  }
//}

function asce_login_denied() {
	global $user;
	$internal_path = substr(request_uri(), strlen(base_path()));
	//drupal_set_message($internal_path);
	if ($user->uid == 0) {
		if ($internal_path == 'peurifoy/2011') {
			menu_set_active_item('user');
			$message = 'Welcome to the Peurifoy Award Selection site. In order to cast your vote ';
			$message .= 'please login below.';
			$return = t($message);
			$return .= menu_execute_active_handler();
		  drupal_set_title(t('2011 Peurifoy Award Selection Committee'));
    	drupal_set_message(t('Access denied.  You may need to login below or register to access this page.'), 'error');
		}
		else {
			$return = logintoboggan_denied();
		}
	}
	return $return;
}

function asce_login_form_alter(&$form, &$form_state, $form_id) {
	if ($form_id == 'user_register') {
		$array = 'asce_login_register_validate';
		array_unshift($form['#validate'], $array);
		//$array = 'asce_login_register_submit';
    //array_unshift($form['#submit'], $array);
		$form['account']['name']['#access'] = FALSE;
		$form['account']['name']['#required'] = FALSE;
		$form['#submit'][] = 'asce_login_register_submit';
		//drupal_set_message(print_r($form['#submit'], TRUE));
		//dsm($form['#validate']);
		//dsm($form['#submit']);
	}
	if ($form_id == 'user_profile_form') {
		if ($form['_category'] == 'account') {
		  //dsm($form);
		}
	}
}

function asce_login_register_validate($form, &$form_state) {
  $form_state['values']['name'] = $form_state['values']['mail'];
}

function asce_login_register_submit($form, &$form_state) {
  drupal_goto('new-account');
}

function asce_login_new_account() {
    global $_domain;
    //$site_mail = domain_conf_variable_get($_domain['domain_id'], 'site_mail');
    $message = '<p>Your password and further instructions have been sent to your e-mail address. If you do not receive an email ';
    $message .=  'it is likely that your email server\'s spam filter quarantied the e-mail. Please be sure to check your spam ';
    $message .= t('box.') . '</p>'; // and add !site_mail to your filters to ensure you receive future emails from us.', array('!site_mail' => $site_mail)) . '</p>';
	  //$message = check_markup($message, 2);
	  return $message;
}

function asce_login_block ($op = 'list', $delta = 0, $edit = array()) {
	if ($op == 'list') {
		$blocks[0]['info'] = t('Status Messages');
    $blocks[0]['cache'] = BLOCK_NO_CACHE;
    
    return $blocks;
	}
	if ($op == 'view') {
		switch ($delta) {
      case 0:
        $block['suject'] = 'Status';
        drupal_set_message('Test');
        $block['content'] = 'Messages should appear here:' . theme('status_messages');
        break;
		}
		return $block;
	}
 
}
