<?php
function ci_linkedin_menu() {
	$items['ci-li/js/check-id'] = array(
    'title' => t('Check for LinkedIn ID'),
    'description' => t('Check for LinkedIn ID'),
    'page callback' => 'ci_linkedin_js_check_id',
    'access callback' => TRUE,
  );
	$items['ci-li/js/check-email'] = array(
    'title' => t('Check for Email'),
    'description' => t('Check for Email'),
    'page callback' => 'ci_linkedin_js_check_email',
    'access callback' => TRUE,
  );
	$items['ci-li/activate'] = array(
    'title' => t('Activate Login with LinkedIn'),
    'description' => t('Links a users LinkedIn account to the CI account'),
    'page callback' => 'ci_linkedin_activate',
    'access callback' => 'user_is_logged_in',
  );
	$items['ci-linkedin/register'] = array(
    'title' => t('Register with Login with Facebook'),
    'description' => t('Create an account using Facebook info'),
    'page callback' => 'ci_linkedin_register',
    'access callback' => 'user_is_anonymous',
  );
	return $items;
}

/**
 * Menu callback.
 * this function is called when the user clicks on the Login w/FB
 * button. It checks to see if the users FB email already exists
 * in the drupal database. If it does, it creates an entry in the
 * {authmap} table using user_set_authmaps and it also creates an
 * entry in {ci_linkedin} to store the users FB ID.
 */
function ci_linkedin_js_check_id() {
	if($account = user_get_authmaps('linkedin:' . $_GET['id'])) {
		ci_linkedin_authenticate('linkedin:' . $_GET['id']);
		$id->found = true;
		return drupal_json($id);
	}
	else {
		// An id was not found so we need to ask the user for a few
		// things
		$id->id = $_GET['id'];
		$id->found = FALSE;
		return drupal_json($id);
	}
}

function ci_linkedin_js_check_email() {
	$email = $_GET['email'];
	
	if($account = user_get_authmaps('linkedin:' . $_GET['id'])) {
		ci_linkedin_authenticate('linkedin:' . $_GET['id']);
		$id->found = true;
		return drupal_json($id);
	}
	else {
		// An id was not found so we need to ask the user for a few
		// things
		$id->id = $_GET['id'];
		$id->found = FALSE;
		return drupal_json($id);
	}
}

function ci_linkedin_authenticate($authname) {
  $account = user_external_load($authname);
  if (isset($account->uid)) {
    if (!variable_get('user_email_verification', TRUE) || $account->login) {
      user_external_login($account, $_SESSION['openid']['user_login_values']);
    }
    else {
      drupal_set_message(t('You must validate your email address for this account before logging in via OpenID'));
    }
  }
}

/*
 * Implementation of hook_form_alter : adds OpenID login to the login forms.
 */
function ci_linkedin_form_alter(&$form, $form_state, $form_id) {
  if ($form_id == 'user_login_block' || $form_id == 'user_login') {
  	$form['fb_links'] = !isset($form['fb_links']) ? array() : $form['fb_links'];
  	$items = array(theme('ci_linkedin'));
		$link = array(
      '#value' => theme('item_list', $items),
      '#weight' => 1,
    );
    $form['fb_links'][] = $link;
  }
  return $form;
}

/**
 * Implementation of hook_block().
 */
function ci_linkedin_block($op = 'list', $delta = 0, $edit = array()) {
  global $user;
	
  if ($op == 'list') {
    $blocks[0]['info'] = t('LinkedIn login');
    // Not worth caching.
    return $blocks;
  }
  else if ($op == 'view') {
    $block = array();

    switch ($delta) {
      case 0:
        // For usability's sake, avoid showing two login forms on one page.
        if ((!$user->uid && !(arg(0) == 'user' && !is_numeric(arg(1)))) || user_access('administer nodes')) {

          $block['subject'] = t('LinkedIn login');
          $block['content'] = 'Nothing';//ci_linkedin_login_block();
        }
        return $block;
    }
  }
}

function ci_linkedin_activate() {
	global $user;
	$data = json_decode($_GET['data']);
	$account = $user;
	$authmaps = array('authname_ci_linkedin' => 'linkedin:' . $data->id);		
	user_set_authmaps($account, $authmaps);
	// Store the facebook user object_id
	db_query("UPDATE {ci_linkedin} SET li_object_id = '%s' WHERE uid = %d", $data->id, $account->uid);
  if (!db_affected_rows()) {
    @db_query("INSERT INTO {ci_linkedin} (uid, li_object_id) VALUES (%d, '%s')", $account->uid, $data->id);
  }
	drupal_set_message('You can now login directly with the Login with LinkedIn button');
	drupal_goto();
}

function ci_linkedin_register() {
	if (variable_get('user_register', 1)) {
	  // Register new user
	  $form_state['redirect'] = NULL;
	  $form_state['values']['name'] = $_GET['email'];
	  $form_state['values']['mail'] = $_GET['email'];
	  $form_state['values']['pass']  = user_password();
	  $form_state['values']['status'] = variable_get('user_register', 1) == 1;
		$form_state['values']['status'] = variable_get('user_register', 1) == 1;
	  if (empty($form_state['values']['name']) && empty($form_state['values']['mail'])) {
	    drupal_set_message(t('Please complete the registration by filling out the form below. If you already have an account, you can <a href="@login">log in</a> now and add your OpenID under "My account".', array('@login' => url('user/login'))), 'warning');
	    $success = FALSE;
	  }
	  else {
	    $form = drupal_retrieve_form('user_register', $form_state);
	    drupal_prepare_form('user_register', $form, $form_state);
	    drupal_validate_form('user_register', $form, $form_state);
	    $success = !form_get_errors();
	    if (!$success) {
	      drupal_set_message(t('Account registration using the information provided by your OpenID provider failed due to the reasons listed below. Please complete the registration by filling out the form below. If you already have an account, you can <a href="@login">log in</a> now and add your OpenID under "My account".', array('@login' => url('user/login'))), 'warning');
	      // Append form validation errors below the above warning.
	      $messages = drupal_get_messages('error');
	      foreach ($messages['error'] as $message) {
	        drupal_set_message( $message, 'error');
	      }
	    }
	  }
	  if (!$success) {
	    // We were unable to register a valid new user, redirect to standard
	    // user/register and prefill with the values we received.
	    $_SESSION['openid']['values'] = $form_state['values'];
	    // We'll want to redirect back to the same place.
	    $destination = drupal_get_destination();
	    unset($_REQUEST['destination']);
	    drupal_goto('user/register', $destination);
	  }
	  else {
	    $account = user_save('', $form_state['values']);
	    // Terminate if an error occured during user_save().
	    if (!$account) {
	      drupal_set_message(t("Error saving user account."), 'error');
	      drupal_goto();
	    }
	    user_external_login($account);
	  }
		drupal_set_message('Welcome! Thanks a new account was created your Facebook information. Next time you can login with the Lofin with Facebook button.');
	  drupal_goto();
	}
	else {
	  drupal_set_message(t('Only site administrators can create new user accounts.'), 'error');
	}
}

function ci_linkedin_login_block() {
	$o = theme('ci_linkedin');
	//$o .= theme('ci_linkedin_have_email_dialog');
	return $o;
}

function ci_linkedin_theme() {
	return array(
    'ci_linkedin' => array(
			'arguments' => array(),
			'template' => 'ci-linkedin',
		),
    'ci_linkedin_have_email_dialog' => array(
			'arguments' => array(),
			'template' => 'ci-linkedin-have-email-dialog',
		),
	);
}

function ci_linkedin_preprocess(&$vars) {
	global $base_url;
	// All of the necessary js files and css files are in ci_fb.module
	if ($base_url === "http://lc.ci-asce.org") {
		$vars['linkedin_api_key'] = 'df2v80gxu2ba';	
	}
	else if ($base_url === "http://ci-asce.org") {
		$vars['linkedin_api_key'] = '76ckm8ufumrq';
	}
}

function ci_linkedin_preprocess_ci_linkedin_have_email_dialog(&$vars) {
	
}


