<?php
// $Id$

/*
 *  Implementation of hook_enable
 */
function asce_forms_enable() {
	$record->weight = 10;
	$record->filename = drupal_get_path('module', 'asce_forms') . '/asce_forms.module';
	drupal_write_record('system', $record, 'filename');
}

function asce_forms_form_alter(&$form, &$form_state, $form_id) {
  if ($form_id == 'blog_post_node_form') {
  	switch ($_GET['op']) {
  		case 'action':
  		  drupal_set_title('Add an Action Item');
  		  //$form['#field_info']['field_task_due']['required'] = 1;
  		  break;
  		case 'post':
  			drupal_set_title('Add a Post');
  			break;
  			
  	}  
  }
  if ($form_id == 'image_node_form') {
    drupal_set_title('Add an Image');
  }
}
