<?php
/**
 * Implementation of hook_menu().
 */
function asce_cck_menu() {
  $items['admin/asce/list-cck-fields'] = array(
    'title' => 'List CCK Fields',
    'description' => t('Update test for testing notifications.'),
    'access arguments' => array('configure ASCE Mobile Tools'),
    'page callback' => 'asce_cck_list_cck_fields',
  );
  return $items;
  
}

/**
 * Implementation of hook_views_api().
 */
function asce_cck_views_api() {
  return array(
    'api' => 2,
    'path' => drupal_get_path('module', 'asce_cck') . '/includes/views',
  );
}

function asce_cck_list_cck_fields() {
  //$path = drupal_get_path('module', 'content') . '/includes/views/';
  //include $path . 'content.views.inc';
  //dsm(content_views_data());
  
  $path = drupal_get_path('module', 'asce_cck') . '/includes/views/';
  include_once $path . 'asce_cck.views.inc';
  asce_cck_views_data();
  
  return '';
}