<?php

/**
 * Implementation of hook_schema().
 */
function ewri_register_schema() {
  $schema = array();
  return $schema;
}

/**
 * Implementation of hook_uninstall().
 */
function ewri_register_uninstall() {
  // Remove all database tables.
  drupal_uninstall_schema('ewri_register');
}

function ewri_register_install() {
	db_query("UPDATE {system} SET weight = 90 WHERE name = 'ewri_register'");
}

