<?php

/**
 * Implementation of hook_schema().
 */
function asce_student_og_schema() {
  $schema = array();
  return $schema;
}

/**
 * Implementation of hook_uninstall().
 */
function asce_student_og_uninstall() {
  // Remove all database tables.
  drupal_uninstall_schema('asce_student_og');
}

function asce_student_og_install() {
	db_query("UPDATE {system} SET weight = 10 WHERE name = 'asce_student_og'");
}

